version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=dev_pass
  web:
    build: .
    volumes:
      - .:/go/src/github.com/bitbrewers/kopls-converter
    ports:
      - "3000:3000"
    depends_on:
      - db